import { describe, it, expect } from 'vitest';
import { emitBase } from '../../src/emit/base.js';
import { emitSubclass } from '../../src/emit/subclass.js';
import { emitSmoke } from '../../src/emit/smoke.js';
import type { IRElement, PageIR } from '../../src/types.js';

const el = (over: Partial<IRElement>): IRElement => ({
  id: 'el_1', name: 'addToCartButton', nameSource: 'deterministic', kind: 'interactive',
  role: 'button', accessibleName: 'Add to cart', group: 'main', status: 'resolved',
  locator: { scope: null, fragile: false, candidate: { strategy: 'testId', value: 'add-to-cart' } },
  rejected: [], observed: {} as never, ...over,
});

const page: PageIR = {
  routeTemplate: '/product/:param1',
  representativeUrl: 'https://s.test/product/a',
  sampleUrls: ['https://s.test/product/a'],
  className: 'ProductPage',
  pageFingerprint: 'pg_x',
  elements: [
    el({}),
    el({ id: 'el_2', name: 'priceText', kind: 'text', role: null, status: 'resolved',
         locator: { scope: null, fragile: false, candidate: { strategy: 'testId', value: 'price' } } }),
    el({ id: 'el_3', name: 'mysteryButton', status: 'unresolved', locator: null }),
  ],
  collections: [{
    id: 'co_1', name: 'productCard', count: 12,
    item: { scope: null, fragile: false, candidate: { strategy: 'testId', value: 'product-card' } },
  }],
};

describe('emitBase', () => {
  const src = emitBase(page);

  it('starts with the do-not-edit banner', () => {
    expect(src.split('\n')[0]).toBe('// GENERATED BY POMBUILDER — DO NOT EDIT');
  });

  it('emits a getter for each resolved element', () => {
    expect(src).toContain("get addToCartButton(): Locator { return this.page.getByTestId('add-to-cart'); }");
  });

  it('omits unresolved elements from code', () => {
    expect(src).not.toContain('mysteryButton');
  });

  it('records the unresolved count in the header', () => {
    expect(src).toContain('// unresolved: 1');
  });

  it('generates a click action for an interactive element', () => {
    expect(src).toContain('async clickAddToCart(): Promise<void> { await this.addToCartButton.click(); }');
  });

  it('does not generate actions for text elements', () => {
    expect(src).not.toContain('clickPriceText');
  });

  it('emits parameterised collection accessors', () => {
    expect(src).toContain('productCardAt(index: number): Locator');
    expect(src).toContain('productCardByText(text: string): Locator');
  });
});

describe('emitSubclass', () => {
  it('extends the base and carries no banner', () => {
    const src = emitSubclass(page);
    expect(src).toContain('export class ProductPage extends ProductPageBase {');
    expect(src).not.toContain('DO NOT EDIT');
  });
});

describe('emitBase action name collision handling', () => {
  const collisionPage: PageIR = {
    routeTemplate: '/details/:param1',
    representativeUrl: 'https://s.test/details/a',
    sampleUrls: ['https://s.test/details/a'],
    className: 'DetailsPage',
    pageFingerprint: 'pg_collision',
    elements: [
      el({ id: 'el_1', name: 'addToCartButton', kind: 'interactive', role: 'button', status: 'resolved',
           locator: { scope: null, fragile: false, candidate: { strategy: 'testId', value: 'add-to-cart' } } }),
      el({ id: 'el_2', name: 'viewDetailsButton', kind: 'interactive', role: 'button', status: 'resolved',
           accessibleName: 'View details', locator: { scope: null, fragile: false, candidate: { strategy: 'testId', value: 'view-details-btn' } } }),
      el({ id: 'el_3', name: 'viewDetailsLink', kind: 'interactive', role: 'link', status: 'resolved',
           accessibleName: 'View details', locator: { scope: null, fragile: false, candidate: { strategy: 'testId', value: 'view-details-link' } } }),
    ],
    collections: [],
  };

  const src = emitBase(collisionPage);

  it('resolves action name collisions by using full element names', () => {
    // Both elements would reduce to "ViewDetails" when stripped, creating a collision
    // The fix should use full names: "clickViewDetailsButton" and "clickViewDetailsLink"
    expect(src).toContain('async clickViewDetailsButton(): Promise<void> { await this.viewDetailsButton.click(); }');
    expect(src).toContain('async clickViewDetailsLink(): Promise<void> { await this.viewDetailsLink.click(); }');
  });

  it('does not emit a bare clickViewDetails action (the collision)', () => {
    // Verify the bare name (without the role suffix) does NOT appear
    expect(src).not.toContain('async clickViewDetails(): Promise<void>');
  });

  it('keeps short names for non-colliding elements', () => {
    // "addToCartButton" strips to "AddToCart" with no collision, so it keeps the short form
    expect(src).toContain('async clickAddToCart(): Promise<void> { await this.addToCartButton.click(); }');
  });
});

describe('emitSmoke', () => {
  const src = emitSmoke(page);

  it('navigates once and soft-asserts every resolved element', () => {
    expect(src).toContain("await page.goto('https://s.test/product/a')");
    expect(src).toContain('await expect.soft(p.addToCartButton).toHaveCount(1)');
    expect(src).toContain('await expect.soft(p.priceText).toBeVisible()');
  });

  it('does not assert on unresolved elements', () => {
    expect(src).not.toContain('mysteryButton');
  });
});
