// SPDX-License-Identifier: Apache-2.0

import type { IRElement, PageIR } from '../types.js';
import { renderCandidate } from '../locator/render.js';

const BANNER = '// GENERATED BY POMBUILDER — DO NOT EDIT';

function actionFor(e: IRElement): string | null {
  if (e.kind !== 'interactive') return null;
  const cap = e.name[0].toUpperCase() + e.name.slice(1);
  const bare = cap.replace(/(Button|Link|Input|Select|Checkbox|Radio|Tab|MenuItem|Option)$/, '');
  if (e.role === 'textbox' || e.role === 'searchbox') {
    return `  async fill${bare}(value: string): Promise<void> { await this.${e.name}.fill(value); }`;
  }
  if (e.role === 'checkbox' || e.role === 'radio') {
    return `  async check${bare}(): Promise<void> { await this.${e.name}.check(); }`;
  }
  return `  async click${bare}(): Promise<void> { await this.${e.name}.click(); }`;
}

export function emitBase(page: PageIR): string {
  const resolved = page.elements.filter((e) => e.status === 'resolved' && e.locator);
  const unresolved = page.elements.length - resolved.length;

  const getters = resolved.map(
    (e) => `  get ${e.name}(): Locator { return ${renderCandidate(e.locator!)}; }`,
  );

  const collections = page.collections.flatMap((c) => {
    const root = renderCandidate(c.item);
    return [
      `  ${c.name}At(index: number): Locator { return ${root}.nth(index); }`,
      `  ${c.name}ByText(text: string): Locator { return ${root}.filter({ hasText: text }); }`,
      `  get ${c.name}Count(): Promise<number> { return ${root}.count(); }`,
    ];
  });

  const actions = resolved.map(actionFor).filter((a): a is string => a !== null);

  return [
    BANNER,
    `// route: ${page.routeTemplate}`,
    `// page fingerprint: ${page.pageFingerprint}`,
    `// unresolved: ${unresolved}`,
    '',
    "import type { Locator, Page } from '@playwright/test';",
    '',
    `export abstract class ${page.className}Base {`,
    `  static readonly route = '${page.routeTemplate}';`,
    `  static readonly url = '${page.representativeUrl}';`,
    '',
    '  constructor(protected readonly page: Page) {}',
    '',
    ...getters,
    ...(collections.length ? ['', ...collections] : []),
    ...(actions.length ? ['', ...actions] : []),
    '}',
    '',
  ].join('\n');
}
