// SPDX-License-Identifier: Apache-2.0

import type { IRElement, PageIR } from '../types.js';
import { renderCandidate } from '../locator/render.js';

const BANNER = '// GENERATED BY POMBUILDER — DO NOT EDIT';

function computeActionName(e: IRElement, collidingCandidates: Set<string>): string | null {
  if (e.kind !== 'interactive') return null;
  const cap = e.name[0].toUpperCase() + e.name.slice(1);
  const stripped = cap.replace(/(Button|Link|Input|Select|Checkbox|Radio|Tab|MenuItem|Option)$/, '');

  // Determine the base name to use for the action
  let bare: string;
  if (e.role === 'textbox' || e.role === 'searchbox') {
    const candidate = `fill${stripped}`;
    bare = collidingCandidates.has(candidate) ? cap : stripped;
    return `  async fill${bare}(value: string): Promise<void> { await this.${e.name}.fill(value); }`;
  }
  if (e.role === 'checkbox' || e.role === 'radio') {
    const candidate = `check${stripped}`;
    bare = collidingCandidates.has(candidate) ? cap : stripped;
    return `  async check${bare}(): Promise<void> { await this.${e.name}.check(); }`;
  }
  const candidate = `click${stripped}`;
  bare = collidingCandidates.has(candidate) ? cap : stripped;
  return `  async click${bare}(): Promise<void> { await this.${e.name}.click(); }`;
}

export function emitBase(page: PageIR): string {
  const resolved = page.elements.filter((e) => e.status === 'resolved' && e.locator);
  const unresolved = page.elements.length - resolved.length;

  const getters = resolved.map(
    (e) => `  get ${e.name}(): Locator { return ${renderCandidate(e.locator!)}; }`,
  );

  const collections = page.collections.flatMap((c) => {
    const root = renderCandidate(c.item);
    return [
      `  ${c.name}At(index: number): Locator { return ${root}.nth(index); }`,
      `  ${c.name}ByText(text: string): Locator { return ${root}.filter({ hasText: text }); }`,
      `  get ${c.name}Count(): Promise<number> { return ${root}.count(); }`,
    ];
  });

  // Detect candidate action name collisions across all resolved interactive elements
  const candidateCounts = new Map<string, number>();
  for (const e of resolved) {
    if (e.kind !== 'interactive') continue;
    const cap = e.name[0].toUpperCase() + e.name.slice(1);
    const stripped = cap.replace(/(Button|Link|Input|Select|Checkbox|Radio|Tab|MenuItem|Option)$/, '');
    let candidatePrefix: string;
    if (e.role === 'textbox' || e.role === 'searchbox') {
      candidatePrefix = `fill${stripped}`;
    } else if (e.role === 'checkbox' || e.role === 'radio') {
      candidatePrefix = `check${stripped}`;
    } else {
      candidatePrefix = `click${stripped}`;
    }
    candidateCounts.set(candidatePrefix, (candidateCounts.get(candidatePrefix) ?? 0) + 1);
  }

  // Identify which candidates collide (count > 1)
  const collidingCandidates = new Set(
    Array.from(candidateCounts.entries())
      .filter(([, count]) => count > 1)
      .map(([candidate]) => candidate),
  );

  const actions = resolved.map((e) => computeActionName(e, collidingCandidates)).filter((a): a is string => a !== null);

  return [
    BANNER,
    `// route: ${page.routeTemplate}`,
    `// page fingerprint: ${page.pageFingerprint}`,
    `// unresolved: ${unresolved}`,
    '',
    "import type { Locator, Page } from '@playwright/test';",
    '',
    `export abstract class ${page.className}Base {`,
    `  static readonly route = '${page.routeTemplate}';`,
    `  static readonly url = '${page.representativeUrl}';`,
    '',
    '  constructor(protected readonly page: Page) {}',
    '',
    ...getters,
    ...(collections.length ? ['', ...collections] : []),
    ...(actions.length ? ['', ...actions] : []),
    '}',
    '',
  ].join('\n');
}
