// SPDX-License-Identifier: Apache-2.0

import type { PageIR } from '../types.js';
import { q, renderCandidate } from '../locator/render.js';
import { collectionMembers, planActions, type PlannedAction } from '../name/members.js';

const BANNER = '// GENERATED BY POMBUILDER — DO NOT EDIT';

function renderAction(a: PlannedAction): string {
  const target = `this.${a.element.name}`;
  switch (a.verb) {
    case 'fill':
      return `  async ${a.method}(value: string): Promise<void> { await ${target}.fill(value); }`;
    case 'check':
      return `  async ${a.method}(): Promise<void> { await ${target}.check(); }`;
    case 'click':
      return `  async ${a.method}(): Promise<void> { await ${target}.click(); }`;
  }
}

export function emitBase(page: PageIR): string {
  const resolved = page.elements.filter((e) => e.status === 'resolved' && e.locator);
  const unresolved = page.elements.length - resolved.length;
  const fragile = resolved.filter((e) => e.locator!.fragile).length;

  const getters = resolved.map((e) => {
    const line = `  get ${e.name}(): Locator { return ${renderCandidate(e.locator!)}; }`;
    return e.locator!.fragile ? `${line} // fragile: positional CSS path` : line;
  });

  const collections = page.collections.flatMap((c) => {
    const root = renderCandidate(c.item);
    const [at, byText, count] = collectionMembers(c.name);
    return [
      `  ${at}(index: number): Locator { return ${root}.nth(index); }`,
      `  ${byText}(text: string): Locator { return ${root}.filter({ hasText: text }); }`,
      `  get ${count}(): Promise<number> { return ${root}.count(); }`,
    ];
  });

  // Member names are settled by the arbiter in src/name/members.ts before emission, so
  // nothing here re-derives or re-dedupes them.
  const actions = planActions(page)
    .filter((a) => a.element.status === 'resolved' && a.element.locator)
    .map(renderAction);

  return [
    BANNER,
    `// route: ${page.routeTemplate}`,
    `// page fingerprint: ${page.pageFingerprint}`,
    `// unresolved: ${unresolved}`,
    `// fragile: ${fragile}`,
    '',
    "import type { Locator, Page } from '@playwright/test';",
    '',
    `export abstract class ${page.className}Base {`,
    `  static readonly route = ${q(page.routeTemplate)};`,
    `  static readonly url = ${q(page.representativeUrl)};`,
    '',
    '  constructor(protected readonly page: Page) {}',
    '',
    ...getters,
    ...(collections.length ? ['', ...collections] : []),
    ...(actions.length ? ['', ...actions] : []),
    '}',
    '',
  ].join('\n');
}
