// SPDX-License-Identifier: Apache-2.0

import type { PageIR } from '../types.js';
import { q } from '../locator/render.js';

export function emitSmoke(page: PageIR): string {
  const resolved = page.elements.filter((e) => e.status === 'resolved' && e.locator);
  const assertions = resolved.flatMap((e) => [
    `  await expect.soft(p.${e.name}).toHaveCount(1);`,
    `  await expect.soft(p.${e.name}).toBeVisible();`,
  ]);

  return [
    '// GENERATED BY POMBUILDER — DO NOT EDIT',
    '',
    "import { expect, test } from '@playwright/test';",
    `import { ${page.className} } from '../pages/${page.className}.js';`,
    '',
    `test(${q(`${page.className} locators resolve uniquely`)}, async ({ page }) => {`,
    `  await page.goto(${q(page.representativeUrl)});`,
    `  const p = new ${page.className}(page);`,
    ...assertions,
    '});',
    '',
  ].join('\n');
}
